default_stages: [commit, push]
default_language_version:
  python: python3.8.10
repos:
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      require_serial: true
      args:
        [
          "-sn", # Don't display the score
          "--rcfile=src/python/pyproject.toml",
          "--recursive=y"
        ]
- repo: meta
  hooks:
    - id: identity
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
      args: [--maxkb=5000, --enforce-all]
    - id: check-ast
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
      args: [--assume-in-merge]
    - id: check-symlinks
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: \.html$|__init__.py
    - id: forbid-submodules
    - id: mixed-line-ending
    - id: name-tests-test
      exclude: fixtures
    - id: pretty-format-json
      args: [--autofix]
      exclude: \.ipynb$
    - id: requirements-txt-fixer
      exclude: .*pipdeptree.*
    - id: sort-simple-yaml
      files: \.yaml$
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.3
  hooks:
    - id: nbqa-isort
      name: nbqa-isort
      args: ["--settings-path=src/python/pyproject.toml"]
      additional_dependencies: [isort==5.12.0]
    - id: nbqa-black
      name: nbqa-black
      args: ["--config=src/python/pyproject.toml"]
      additional_dependencies: [black==23.1.0]
    - id: nbqa-pylint
      name: nbqa-pylint
      args: ["--rcfile=src/python/pyproject.toml", "--recursive=y", "-sn"]
      additional_dependencies: [pylint==2.16.4]
      verbose: true
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      args: ["--settings-path=src/python/pyproject.toml"]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      args: ["--config=src/python/pyproject.toml"]
