[tool.black]
line-length = 90 # override black's default line-length
force-exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# make it compatible with black
profile = "black"
atomic = true
combine_as_imports = true
line_length = 90
known_first_party = ["epi_ml", "src"]
src_paths = ["epi_ml/**", "src"]
known_local_folder = ["epi_ml/**", "src"]

[tool.pyright]
include = ["src"]
exclude = [
    "**/__pycache__",
    "**/epilap",
    "**/notes",
    ".git"
    ]
