[tool.black]
line-length = 90 # override black's default line-length
force-exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.isort]
# make it compatible with black
profile = "black"
atomic = true
combine_as_imports = true
line_length = 90
known_first_party = ["epi_ml", "tests"]
known_local_folder = ["./epi_ml", "./tests"]
src_paths = ["./epi_ml/**", "./tests/**"]


[tool.pyright]
ignore = [
    "**/epilap/**",
    "**/notes",
    ".git",
    "**/bin/**",
    "**/site-packages/**",
    "venv-epilap-pytorch",
]
exclude = ["**/notes", "**/epilap/**", ".git", "**/bin/**", "**/lib/**"]

[tool.pylint.MASTER]
ignore-paths = ["venv-epilap-pytorch"]

[tool.pylint.main]
extension-pkg-allow-list = [
    "numpy",
    "torch",
    "pytorch_lightning",
    "optuna.integration.lightgbm",
    "pyBigWig",
]

[tool.pylint.messages_control]
disable = [
    "abstract-method",
    "bad-inline-option",
    "deprecated-pragma",
    "file-ignored",
    "invalid-name",
    "line-too-long",
    "locally-disabled",
    "suppressed-message",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
    "too-many-locals",
    "too-many-statements",
    "use-symbolic-message-instead",
    "useless-suppression",
    "wrong-import-order",
    "wrong-import-position",
]

[tool.pylint.typecheck]
generated-members = [
    "numpy.*",
    "torch.*",
    "pytorch_lightning.*",
    "optuna.integration.lightgbm.*",
    "pyBigWig.*",
]

[tool.pylint.format]
max-line-length = 120


[tool.pytest.ini_options]
testpaths = ["tests"]
minversion = "6.0"
filterwarnings = [
    "ignore::DeprecationWarning:jupyter_client.*",
    "ignore::DeprecationWarning:comet_ml.monkey_patching",
    "ignore:.*declarative_base.*",
    "ignore:.*nopython.*",
    "ignore:.*Using a non-full backward hook.*",
    "ignore:.*`np.bool` is a deprecated alias.*",
    "ignore:.*Cannot read file directly.*",
]
# action:message:category:module:line
