project:
  output-dir: "../../../../../../../../../docs/epiclass-paper"
  post-render: "./remove-website-resources.sh"
  type: website
  preview:
    watch-inputs: true   # automatically rebuild on save
    navigate: true       # live navigation without full reload
    browser: true        # open browser automatically
    port: 4444

website:
  title: "EpiClass paper - Figures"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: "![GitHub](https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/icons/github.svg 'View source code on GitHub')"
        href: https://github.com/rabyj/EpiClass/tree/master
        aria-label: View source code on GitHub
      - text: "![Model on HF](https://huggingface.co/datasets/huggingface/badges/resolve/main/model-on-hf-sm.svg 'Access EpiClass models on HuggingFace')"
        href: https://huggingface.co/collections/KatLeChat/epiclass-models-68adb5ce65c8f2fb93322e59
        aria-label: Access EpiClass models on HuggingFace

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
